### ISSUE TITLE
jpg orientation changes

### ISSUE THREAD

**Issue by Antony74** [JayXon/Leanify#20]
Here's one of my wedding photos.  What happens when you try to Leanify it, please?

http://akb.me.uk/IMG_2575.jpg

When I try, the orientation changes from portrait to landscape.  I think this might be a bug, and the orientation should stay the same?

![grab](https://cloud.githubusercontent.com/assets/1577335/13442865/33430904-dff6-11e5-8314-bdac6c74879f.png)

**Comment by JayXon** [comment]
Thanks for your report!
The image is indeed stored in landscape, you were seeing it in portrait before is because there's orientation information in the exif.
Take a look at the exif information of your image here: http://regex.info/exif.cgi?imgurl=http%3A%2F%2Fakb.me.uk%2FIMG_2575.jpg
In the orientation section, it tells the viewer to rotate the image 270 degree clockwise.
However, currently leanify removes exif by default, try to use `--keep-exif`, and the orientation should not change.
For personal photos that you want to keep on your disk, I would recommend always keep the exif, as it may also contains information about the time the photo is taken, the camera you're using, etc. However, if you are going to post it on your website, you probably want to make it as small as possible to save your website bandwidth and make your website load faster and you might not want people to know too much detail like the location where the photo is taken.
I think leanify probably should be more smart at this, e.g. keep exif if there's orientation in it, or maybe keep exif by default and provide another option to remove it.

**Comment by Antony74** [comment]
Thank you very much for your response - and your insight into the curious world of file formats!

**Comment by Antony74** [comment]
> e.g. keep exif if there's orientation in it, or maybe keep exif by default and provide another option to remove it.

I'd probably go with "print a warning if an exif with orientation in it is removed" since that keeps everything else about the behavior of Leanify exactly as it was.

By the way, if I run Leanify without any parameters, then it displays usage information which doesn't mention the --keep-exif option.

**Comment by JayXon** [comment]
Thanks for the suggestion, warning sounds good.
Are you sure --keep-exif is not there? It's the last option, what version are you using?

**Comment by Antony74** [comment]
Sorry, my mistake.  The [Chocolately package](https://chocolatey.org/packages/leanify) is one version out of date.

![leanify](https://cloud.githubusercontent.com/assets/1577335/14202536/6eda47f4-f7f0-11e5-98d7-c7334fbefdce.png)
