### ISSUE TITLE
Zip "stored" files

### ISSUE THREAD

**Issue by andrews05** [JayXon/Leanify#42]
There's a comment in zip.cpp:218 regarding files using the store method: "don't try to change it to deflate, it might break some file"
Can you elaborate on this? I note that the advzip program does compress stored files.

**Comment by JayXon** [comment]
I did this because in some cases the file has to be stored otherwise it will be invalid, for example the `mimetype` file in epub must be uncompressed https://en.wikipedia.org/wiki/EPUB#Container
It's not really possible for me to write special code for all these cases out there, so in order to be on the safe side I chose to not change that, however I could probably add an option to force try to compress it if that's what the user want.

**Comment by andrews05** [comment]
Okay, thanks for the clarification. I think such an option would be helpful. Alternatively, what if you compress automatically for plain ".zip" files but err on the safe side for any other extension?

(I tested an ePub file, seems programs don't actually care if the mimetype isn't even present. Recompressing it with advzip didn't compress the mimetype though, presumably because it's too small.)
