### ISSUE TITLE
CBR/RAR Support

### ISSUE THREAD

**Issue by Wdavery** [JayXon/Leanify#53]
CBZ and CBT are used far less than CBR these days, it seems to be the primary format. Is support for RARs a possibility?

**Comment by JayXon** [comment]
unlikely, rar isn't an open format

**Comment by JayXon** [comment]
I'm going to close this because it can't be supported unless there's an open source library that can compress and decompress rar.

What you could do as a workaround is to manually decompress the rar into a folder, run Leanify on that folder, and then compress that folder back to CBR file. It should be easy to write a script to do this too.
